export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
